//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApp.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bill.
        /// </summary>
        internal static string addBill {
            get {
                return ResourceManager.GetString("addBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add client.
        /// </summary>
        internal static string addClient {
            get {
                return ResourceManager.GetString("addClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully.
        /// </summary>
        internal static string addedSuccessfully {
            get {
                return ResourceManager.GetString("addedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Image.
        /// </summary>
        internal static string addImage {
            get {
                return ResourceManager.GetString("addImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Market.
        /// </summary>
        internal static string addMarket {
            get {
                return ResourceManager.GetString("addMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offer.
        /// </summary>
        internal static string addOffer {
            get {
                return ResourceManager.GetString("addOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Price.
        /// </summary>
        internal static string addPrice {
            get {
                return ResourceManager.GetString("addPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Details.
        /// </summary>
        internal static string addressDetails {
            get {
                return ResourceManager.GetString("addressDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address so short.
        /// </summary>
        internal static string addressSoShort {
            get {
                return ResourceManager.GetString("addressSoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shop.
        /// </summary>
        internal static string addShop {
            get {
                return ResourceManager.GetString("addShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All installments at day.
        /// </summary>
        internal static string allInDay {
            get {
                return ResourceManager.GetString("allInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All received installments today.
        /// </summary>
        internal static string allReceivedToday {
            get {
                return ResourceManager.GetString("allReceivedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All today installments.
        /// </summary>
        internal static string allToday {
            get {
                return ResourceManager.GetString("allToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unreceived installments.
        /// </summary>
        internal static string allUnReceived {
            get {
                return ResourceManager.GetString("allUnReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All unreceived installments today.
        /// </summary>
        internal static string allUnReceivedToday {
            get {
                return ResourceManager.GetString("allUnReceivedToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount paid.
        /// </summary>
        internal static string amountPaid {
            get {
                return ResourceManager.GetString("amountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount value.
        /// </summary>
        internal static string amountValue {
            get {
                return ResourceManager.GetString("amountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell your products from your place.
        /// </summary>
        internal static string appDescription {
            get {
                return ResourceManager.GetString("appDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mina Top.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average price.
        /// </summary>
        internal static string averagePrice {
            get {
                return ResourceManager.GetString("averagePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        internal static string bill {
            get {
                return ResourceManager.GetString("bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill date.
        /// </summary>
        internal static string billDate {
            get {
                return ResourceManager.GetString("billDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill details.
        /// </summary>
        internal static string billDetails {
            get {
                return ResourceManager.GetString("billDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill installments.
        /// </summary>
        internal static string billInstallments {
            get {
                return ResourceManager.GetString("billInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        internal static string bills {
            get {
                return ResourceManager.GetString("bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel receive.
        /// </summary>
        internal static string cancelReceive {
            get {
                return ResourceManager.GetString("cancelReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string categoty {
            get {
                return ResourceManager.GetString("categoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client bills.
        /// </summary>
        internal static string clientBills {
            get {
                return ResourceManager.GetString("clientBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client details.
        /// </summary>
        internal static string clientDetails {
            get {
                return ResourceManager.GetString("clientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name.
        /// </summary>
        internal static string clientName {
            get {
                return ResourceManager.GetString("clientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment so short.
        /// </summary>
        internal static string commentSoShort {
            get {
                return ResourceManager.GetString("commentSoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Successfully.
        /// </summary>
        internal static string completedSuccessfully {
            get {
                return ResourceManager.GetString("completedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete registration.
        /// </summary>
        internal static string completeRegistration {
            get {
                return ResourceManager.GetString("completeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created successfully.
        /// </summary>
        internal static string createdSuccessfully {
            get {
                return ResourceManager.GetString("createdSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string daily {
            get {
                return ResourceManager.GetString("daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of delay.
        /// </summary>
        internal static string daysOfDelay {
            get {
                return ResourceManager.GetString("daysOfDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay fine.
        /// </summary>
        internal static string delayFine {
            get {
                return ResourceManager.GetString("delayFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay fine type.
        /// </summary>
        internal static string delayFineType {
            get {
                return ResourceManager.GetString("delayFineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete bill.
        /// </summary>
        internal static string deleteBill {
            get {
                return ResourceManager.GetString("deleteBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Client.
        /// </summary>
        internal static string deleteClient {
            get {
                return ResourceManager.GetString("deleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        internal static string deletedSuccessfully {
            get {
                return ResourceManager.GetString("deletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Offer.
        /// </summary>
        internal static string deleteOffer {
            get {
                return ResourceManager.GetString("deleteOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description so short.
        /// </summary>
        internal static string descriptionSoShort {
            get {
                return ResourceManager.GetString("descriptionSoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        internal static string dueDate {
            get {
                return ResourceManager.GetString("dueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bill.
        /// </summary>
        internal static string editBill {
            get {
                return ResourceManager.GetString("editBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit client.
        /// </summary>
        internal static string editClient {
            get {
                return ResourceManager.GetString("editClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone is already used.
        /// </summary>
        internal static string emailOrPhoneUsed {
            get {
                return ResourceManager.GetString("emailOrPhoneUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Sell.
        /// </summary>
        internal static string forSell {
            get {
                return ResourceManager.GetString("forSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required.
        /// </summary>
        internal static string fullNameRequired {
            get {
                return ResourceManager.GetString("fullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string getStarted {
            get {
                return ResourceManager.GetString("getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From now you can market your product yourself.
        /// </summary>
        internal static string hint1 {
            get {
                return ResourceManager.GetString("hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wherever you are, at any time, there are always those looking for your production.
        /// </summary>
        internal static string hint2 {
            get {
                return ResourceManager.GetString("hint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It helps you sell your products as quickly as possible at an affordable price without middlemen.
        /// </summary>
        internal static string hint3 {
            get {
                return ResourceManager.GetString("hint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment.
        /// </summary>
        internal static string installment {
            get {
                return ResourceManager.GetString("installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment count.
        /// </summary>
        internal static string installmentCount {
            get {
                return ResourceManager.GetString("installmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment details.
        /// </summary>
        internal static string installmentDetails {
            get {
                return ResourceManager.GetString("installmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installments.
        /// </summary>
        internal static string installments {
            get {
                return ResourceManager.GetString("installments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment type.
        /// </summary>
        internal static string installmentType {
            get {
                return ResourceManager.GetString("installmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to market added successfully.
        /// </summary>
        internal static string marketAddedSuccessfully {
            get {
                return ResourceManager.GetString("marketAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Details.
        /// </summary>
        internal static string marketDetails {
            get {
                return ResourceManager.GetString("marketDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Name.
        /// </summary>
        internal static string marketName {
            get {
                return ResourceManager.GetString("marketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market name so short.
        /// </summary>
        internal static string marketNameSoShort {
            get {
                return ResourceManager.GetString("marketNameSoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets.
        /// </summary>
        internal static string markets {
            get {
                return ResourceManager.GetString("markets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Shops.
        /// </summary>
        internal static string marketShops {
            get {
                return ResourceManager.GetString("marketShops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile / email.
        /// </summary>
        internal static string mobileOrEmail {
            get {
                return ResourceManager.GetString("mobileOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile or email required.
        /// </summary>
        internal static string mobileOrEmailRequired {
            get {
                return ResourceManager.GetString("mobileOrEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Offers.
        /// </summary>
        internal static string myOffers {
            get {
                return ResourceManager.GetString("myOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name so short.
        /// </summary>
        internal static string nameSoShort {
            get {
                return ResourceManager.GetString("nameSoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not correct.
        /// </summary>
        internal static string notCorrect {
            get {
                return ResourceManager.GetString("notCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offer added successfully.
        /// </summary>
        internal static string offerAddedSuccessfully {
            get {
                return ResourceManager.GetString("offerAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Details.
        /// </summary>
        internal static string offerDetails {
            get {
                return ResourceManager.GetString("offerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Type.
        /// </summary>
        internal static string offerType {
            get {
                return ResourceManager.GetString("offerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original amount.
        /// </summary>
        internal static string originalAmount {
            get {
                return ResourceManager.GetString("originalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        internal static string ownerName {
            get {
                return ResourceManager.GetString("ownerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name so short.
        /// </summary>
        internal static string ownerNameSoShort {
            get {
                return ResourceManager.GetString("ownerNameSoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not matched.
        /// </summary>
        internal static string passNotMatched {
            get {
                return ResourceManager.GetString("passNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        internal static string passRequired {
            get {
                return ResourceManager.GetString("passRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string percentage {
            get {
                return ResourceManager.GetString("percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string personalInfo {
            get {
                return ResourceManager.GetString("personalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone so short.
        /// </summary>
        internal static string phoneSoShort {
            get {
                return ResourceManager.GetString("phoneSoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call 01111257052 to activate your account.
        /// </summary>
        internal static string pleaseCallToActivateAccount {
            get {
                return ResourceManager.GetString("pleaseCallToActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete registration.
        /// </summary>
        internal static string pleaseCompleteRegistration {
            get {
                return ResourceManager.GetString("pleaseCompleteRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login or register to continue.
        /// </summary>
        internal static string pleaseLoginOrRefisterToContinue {
            get {
                return ResourceManager.GetString("pleaseLoginOrRefisterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure the internet connection is open.
        /// </summary>
        internal static string pleaseOpenNetConn {
            get {
                return ResourceManager.GetString("pleaseOpenNetConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re login.
        /// </summary>
        internal static string pleaseReLogin {
            get {
                return ResourceManager.GetString("pleaseReLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select category.
        /// </summary>
        internal static string pleaseSelectCategory {
            get {
                return ResourceManager.GetString("pleaseSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select city.
        /// </summary>
        internal static string pleaseSelectCity {
            get {
                return ResourceManager.GetString("pleaseSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select country.
        /// </summary>
        internal static string pleaseSelectCountry {
            get {
                return ResourceManager.GetString("pleaseSelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select product.
        /// </summary>
        internal static string pleaseSelectProduct {
            get {
                return ResourceManager.GetString("pleaseSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select quantity type.
        /// </summary>
        internal static string pleaseSelectQuantityType {
            get {
                return ResourceManager.GetString("pleaseSelectQuantityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user type.
        /// </summary>
        internal static string pleaseSelectUserType {
            get {
                return ResourceManager.GetString("pleaseSelectUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        internal static string pleaseTryAgain {
            get {
                return ResourceManager.GetString("pleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait ....
        /// </summary>
        internal static string pleaseWait {
            get {
                return ResourceManager.GetString("pleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write good comment.
        /// </summary>
        internal static string pleaseWriteGoodComment {
            get {
                return ResourceManager.GetString("pleaseWriteGoodComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write good description.
        /// </summary>
        internal static string pleaseWriteGoodDescription {
            get {
                return ResourceManager.GetString("pleaseWriteGoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price added successfully.
        /// </summary>
        internal static string priceAddedSuccessfully {
            get {
                return ResourceManager.GetString("priceAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Required.
        /// </summary>
        internal static string priceRequired {
            get {
                return ResourceManager.GetString("priceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        internal static string prices {
            get {
                return ResourceManager.GetString("prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity required.
        /// </summary>
        internal static string quantityRequired {
            get {
                return ResourceManager.GetString("quantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Type.
        /// </summary>
        internal static string quantityType {
            get {
                return ResourceManager.GetString("quantityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string receive {
            get {
                return ResourceManager.GetString("receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string received {
            get {
                return ResourceManager.GetString("received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received date.
        /// </summary>
        internal static string receivedDate {
            get {
                return ResourceManager.GetString("receivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest amount.
        /// </summary>
        internal static string restAmount {
            get {
                return ResourceManager.GetString("restAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shop added successfully.
        /// </summary>
        internal static string shopAddedSuccessfully {
            get {
                return ResourceManager.GetString("shopAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Details.
        /// </summary>
        internal static string shopDetails {
            get {
                return ResourceManager.GetString("shopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Name.
        /// </summary>
        internal static string shopName {
            get {
                return ResourceManager.GetString("shopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop name so short.
        /// </summary>
        internal static string shopNameSoShort {
            get {
                return ResourceManager.GetString("shopNameSoShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong.
        /// </summary>
        internal static string somethingWrong {
            get {
                return ResourceManager.GetString("somethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this item?.
        /// </summary>
        internal static string sureToDelete {
            get {
                return ResourceManager.GetString("sureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to edit this item?.
        /// </summary>
        internal static string sureToEdit {
            get {
                return ResourceManager.GetString("sureToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to update this item?.
        /// </summary>
        internal static string sureToUpdate {
            get {
                return ResourceManager.GetString("sureToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Entry.
        /// </summary>
        internal static string temporaryEntry {
            get {
                return ResourceManager.GetString("temporaryEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Buy.
        /// </summary>
        internal static string toBuy {
            get {
                return ResourceManager.GetString("toBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string totalAmount {
            get {
                return ResourceManager.GetString("totalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total delay fine.
        /// </summary>
        internal static string totalDelayFine {
            get {
                return ResourceManager.GetString("totalDelayFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully.
        /// </summary>
        internal static string updatedSuccessfully {
            get {
                return ResourceManager.GetString("updatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect.
        /// </summary>
        internal static string userOrPassIncorrect {
            get {
                return ResourceManager.GetString("userOrPassIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        internal static string userType {
            get {
                return ResourceManager.GetString("userType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Shops.
        /// </summary>
        internal static string viewShops {
            get {
                return ResourceManager.GetString("viewShops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to you.
        /// </summary>
        internal static string welcomeToYou {
            get {
                return ResourceManager.GetString("welcomeToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Comment.
        /// </summary>
        internal static string writeComment {
            get {
                return ResourceManager.GetString("writeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write here to search.
        /// </summary>
        internal static string writeHereToSearch {
            get {
                return ResourceManager.GetString("writeHereToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string yearly {
            get {
                return ResourceManager.GetString("yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
